//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppHealth.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.Invoices = new HashSet<Invoice>();
            this.MedicalRecords = new HashSet<MedicalRecord>();
        }
    
        public int AppointmentID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Symptoms { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string CCCD { get; set; }
        public string Address { get; set; }
        public Nullable<bool> HasHealthInsurance { get; set; }
        public string HealthInsuranceNumber { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public string TimeSlot { get; set; }
        public Nullable<bool> IsConfirm { get; set; }
        public string AppointmentCode { get; set; }
        public Nullable<int> DoctorID { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual Service Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalRecord> MedicalRecords { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
