//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppHealth.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Gender { get; set; }
        public string IdentityCard { get; set; }
        public System.DateTime IssueDate { get; set; }
        public string IssuePlace { get; set; }
        public string Hometown { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Qualification { get; set; }
        public string School { get; set; }
        public string TrainingSystem { get; set; }
        public int GraduationYear { get; set; }
        public string Rank { get; set; }
        public string LanguageCert { get; set; }
        public string InformaticsCert { get; set; }
        public string Experience { get; set; }
        public string CvUrl { get; set; }
        public string CertUrls { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
