//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppHealth.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicalRecord()
        {
            this.PrescriptionDetails = new HashSet<PrescriptionDetail>();
        }
    
        public int RecordID { get; set; }
        public Nullable<int> AppointmentID { get; set; }
        public string Diagnosis { get; set; }
        public string DoctorNotes { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> DoctorID { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrescriptionDetail> PrescriptionDetails { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
