//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppHealth.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicine()
        {
            this.PrescriptionDetails = new HashSet<PrescriptionDetail>();
        }
    
        public int MedicineID { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Image { get; set; }
        public string ActiveIngredient { get; set; }
        public string Concentration { get; set; }
        public string DrugGroup { get; set; }
        public string DosageForm { get; set; }
        public string Manufacturer { get; set; }
        public string Packaging { get; set; }
        public string InstructionFile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrescriptionDetail> PrescriptionDetails { get; set; }
    }
}
