//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppHealth.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptionDetail
    {
        public int PrescriptionID { get; set; }
        public Nullable<int> RecordID { get; set; }
        public Nullable<int> MedicineID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string UsageInstruction { get; set; }
    
        public virtual MedicalRecord MedicalRecord { get; set; }
        public virtual Medicine Medicine { get; set; }
    }
}
