//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppHealth.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOTP
    {
        public int OTPID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Code { get; set; }
        public string OtpType { get; set; }
        public Nullable<System.DateTime> ExpiredAt { get; set; }
    
        public virtual User User { get; set; }
    }
}
